package com.model;

/**
 * TJiaoyuan generated by MyEclipse Persistence Tools
 */

public class TJiaoyuan implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String loginname;

	private String loginpw;

	private String name;

	private String sex;

	private String age;

	private String tel;

	private String address;

	private String shenfen;

	private String xueli;

	private String kefudaokemu;

	private String ziwojieshao;
	
	private String fujian;

	private String del;

	// Constructors

	/** default constructor */
	public TJiaoyuan()
	{
	}

	/** full constructor */
	public TJiaoyuan(String loginname, String loginpw, String name, String sex,
			String age, String tel, String address, String shenfen,
			String xueli, String kefudaokemu, String ziwojieshao, String del)
	{
		this.loginname = loginname;
		this.loginpw = loginpw;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.tel = tel;
		this.address = address;
		this.shenfen = shenfen;
		this.xueli = xueli;
		this.kefudaokemu = kefudaokemu;
		this.ziwojieshao = ziwojieshao;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getLoginname()
	{
		return this.loginname;
	}

	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}

	public String getLoginpw()
	{
		return this.loginpw;
	}

	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}

	public String getName()
	{
		return this.name;
	}

	public String getFujian()
	{
		return fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getSex()
	{
		return this.sex;
	}

	public void setSex(String sex)
	{
		this.sex = sex;
	}

	public String getAge()
	{
		return this.age;
	}

	public void setAge(String age)
	{
		this.age = age;
	}

	public String getTel()
	{
		return this.tel;
	}

	public void setTel(String tel)
	{
		this.tel = tel;
	}

	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	public String getShenfen()
	{
		return this.shenfen;
	}

	public void setShenfen(String shenfen)
	{
		this.shenfen = shenfen;
	}

	public String getXueli()
	{
		return this.xueli;
	}

	public void setXueli(String xueli)
	{
		this.xueli = xueli;
	}

	public String getKefudaokemu()
	{
		return this.kefudaokemu;
	}

	public void setKefudaokemu(String kefudaokemu)
	{
		this.kefudaokemu = kefudaokemu;
	}

	public String getZiwojieshao()
	{
		return this.ziwojieshao;
	}

	public void setZiwojieshao(String ziwojieshao)
	{
		this.ziwojieshao = ziwojieshao;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}