package com.model;

/**
 * TXueyuan generated by MyEclipse Persistence Tools
 */

public class TXueyuan implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String loginname;

	private String loginpw;

	private String name;

	private String sex;

	private String age;

	private String tel;

	private String address;

	private String fudaokemu;

	private String xueyuanqingkuang;

	private String jiaoyuanyaoqiu;
	
	private String del;

	// Constructors

	/** default constructor */
	public TXueyuan()
	{
	}

	/** full constructor */
	public TXueyuan(String loginname, String loginpw, String name, String sex,
			String age, String tel, String address, String fudaokemu,
			String xueyuanqingkuang, String jiaoyuanyaoqiu)
	{
		this.loginname = loginname;
		this.loginpw = loginpw;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.tel = tel;
		this.address = address;
		this.fudaokemu = fudaokemu;
		this.xueyuanqingkuang = xueyuanqingkuang;
		this.jiaoyuanyaoqiu = jiaoyuanyaoqiu;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getLoginname()
	{
		return this.loginname;
	}

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}

	public String getLoginpw()
	{
		return this.loginpw;
	}

	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getSex()
	{
		return this.sex;
	}

	public void setSex(String sex)
	{
		this.sex = sex;
	}

	public String getAge()
	{
		return this.age;
	}

	public void setAge(String age)
	{
		this.age = age;
	}

	public String getTel()
	{
		return this.tel;
	}

	public void setTel(String tel)
	{
		this.tel = tel;
	}

	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	public String getFudaokemu()
	{
		return this.fudaokemu;
	}

	public void setFudaokemu(String fudaokemu)
	{
		this.fudaokemu = fudaokemu;
	}

	public String getXueyuanqingkuang()
	{
		return this.xueyuanqingkuang;
	}

	public void setXueyuanqingkuang(String xueyuanqingkuang)
	{
		this.xueyuanqingkuang = xueyuanqingkuang;
	}

	public String getJiaoyuanyaoqiu()
	{
		return this.jiaoyuanyaoqiu;
	}

	public void setJiaoyuanyaoqiu(String jiaoyuanyaoqiu)
	{
		this.jiaoyuanyaoqiu = jiaoyuanyaoqiu;
	}

}