package com.model;

/**
 * TYuyue generated by MyEclipse Persistence Tools
 */

public class TYuyue implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer xueyuan_id;

	private Integer jiaoyuan_id;

	private String yuyuezhe_tel;
    
	private String shijian;
	
	private String beizhu;

	private String type;//tojiaoyuan--学员预约教员

	private TXueyuan xueyuan;
	
	private TJiaoyuan jiaoyuan;

	/** default constructor */
	public TYuyue()
	{
	}


	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	


	
	public Integer getJiaoyuan_id()
	{
		return jiaoyuan_id;
	}


	public void setJiaoyuan_id(Integer jiaoyuan_id)
	{
		this.jiaoyuan_id = jiaoyuan_id;
	}


	public String getShijian()
	{
		return shijian;
	}


	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}


	public TJiaoyuan getJiaoyuan()
	{
		return jiaoyuan;
	}


	public void setJiaoyuan(TJiaoyuan jiaoyuan)
	{
		this.jiaoyuan = jiaoyuan;
	}


	public TXueyuan getXueyuan()
	{
		return xueyuan;
	}


	public void setXueyuan(TXueyuan xueyuan)
	{
		this.xueyuan = xueyuan;
	}


	public Integer getXueyuan_id()
	{
		return xueyuan_id;
	}


	public void setXueyuan_id(Integer xueyuan_id)
	{
		this.xueyuan_id = xueyuan_id;
	}


	public String getYuyuezhe_tel()
	{
		return yuyuezhe_tel;
	}


	public void setYuyuezhe_tel(String yuyuezhe_tel)
	{
		this.yuyuezhe_tel = yuyuezhe_tel;
	}


	public String getBeizhu()
	{
		return this.beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public String getType()
	{
		return this.type;
	}

	public void setType(String type)
	{
		this.type = type;
	}

}